mkdir module-1\assignment-1 module-1\assignment-2 module-1\assignment-3
mkdir module-2\assignment-1 module-2\assignment-2 module-2\assignment-3
mkdir module-3\assignment-1 module-3\assignment-2 module-3\assignment-3
mkdir module-4\assignment-1 module-4\assignment-2 module-4\assignment-3
mkdir module-5\assignment-1 module-5\assignment-2 module-5\assignment-3
mkdir module-6\assignment-1 module-6\assignment-2 module-6\assignment-3
mkdir module-7\assignment-1 module-7\assignment-2 module-7\assignment-3
mkdir module-8\assignment-1 module-8\assignment-2 module-8\assignment-3
mkdir module-9\assignment-1 module-9\assignment-2 module-9\assignment-3
mkdir module-10\assignment-1 module-10\assignment-2 module-10\assignment-3
mkdir module-11\assignment-1 module-11\assignment-2 module-11\assignment-3
mkdir module-12\assignment-1 module-12\assignment-2 module-12\assignment-3
